export const TAGS = {
  GET_ALL_USER: 'get_all_user',
  GET_USER_ROLES: 'get_user_roles',
  GET_USER: 'get_user',
  GET_ME: 'get_me',
  GET_ALL_ROLES: 'get_all_roles',
  GET_ROLE: 'get_role',
  GET_ALL_CAMPAIGNS: 'get_all_campaign',
  GET_CAMPAIGNS: 'get_campaign',
  GET_CAMPAIGNS_AUDIO: 'get_campaign_audio',
  GET_ALL_TRANSPORT: 'get_all_transport',
  GET_ALL_AUDIENCE: 'get_all_audience',
  GET_BENEFICIARIES: 'get_beneficiaries',
  GET_BENEFICIARIES_STATUS: 'get_beneficiaries_status',
};
